[build]
  publish = "build"  # Directory to deploy (output of 'npm run build')
  command = "npm run build"  # Build command

[[redirects]]
  from = "/api/generate-1/*"  # Proxy path for the first backend URL
  to = "http://4.242.100.105/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate-2/*"  # Proxy path for the second backend URL
  to = "http://172.179.69.98/:splat"
  status = 200
  force = true
